name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest stable version

      - name: Use Node.js 20
        uses: actions/setup-node@v3  # Use the latest version for Node.js setup
        with:
          node-version: '20'
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Adjust this if your project does not need a build step

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1  # Ensure this is the latest version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Adjust if your code is in a subdirectory
          server-dir: /home/ngslccor/yudomot.techengood.com/  # Your specific path
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env  # Exclude .env file from being overwritten
