name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use Node16 compatible version

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Ensure this is the latest version
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Adjust if your code is in a subdirectory
        server-dir: /home/ngslccor/yudomot.techengood.com/  # Your specific path
