name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4  # Use the latest stable version

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Use the latest version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps  # Use FTPS for secure file transfer
          local-dir: ./  # Adjust if your code is in a subdirectory
          server-dir: /home/ngslccor/yudomot.techengood.com/  # Your specific path
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env  # Exclude .env file from being overwritten
