name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'
      
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Adjust if your code is in a subdirectory
          server-dir: /home/ngslccor/yudomot.techengood.com/  # Your specific path
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env  # Exclude .env file from being overwritten
