name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4  # Use the latest stable version

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Use the latest version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps  # Use FTPS for secure file transfer
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env  # Exclude .env file from being overwritten

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: List and Download error logs
        run: |
          mkdir -p logs  # Create a directory to store downloaded logs
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} <<EOF
          set ssl:verify-certificate no
          lcd logs
          cd /path/to/your/logs  # Change to the directory where logs are stored on the server
          ls *error* || echo "No *error* logs found"
          ls error_log || echo "No error_log found"
          ls laravel.log || echo "No laravel.log found"
          bye
          EOF
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} <<EOF
          set ssl:verify-certificate no
          lcd logs
          cd /path/to/your/logs
          mget *error* || true  # Download files containing 'error' in their name if they exist
          mget error_log || true  # Download 'error_log' if it exists
          mget laravel.log || true  # Download 'laravel.log' if it exists
          bye
          EOF

      - name: Upload logs
        if: always()  # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: logs/
          if-no-files-found: warn  # You can set to 'ignore' or 'error' based on your preference
